steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: [ '-c', 'git fetch --unshallow --tags && git checkout ${BRANCH_NAME}' ]

  - name: 'taktik/git-version:1.0.0-g4b8d2fa5dd'
    args: [ '-f', 'git.version' ]

  - name: 'docker:24'
    entrypoint: 'sh'
    args: [ '-c', 'echo ${_DOCKER_PASSWORD} | docker login --username=${_DOCKER_USERNAME} --password-stdin' ]

  - name: 'docker:24-git'
    entrypoint: 'sh'
    args: [ '-c', 'docker build --push -t taktik/git-version:$(cat git.version) -f docker/Dockerfile . || true # https://github.com/moby/buildkit/issues/3919' ]
